<a href="https://colab.research.google.com/github/MishanyaNoobasik/YaDaun1/blob/main/numpy_dz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math, time, sys
from io import StringIO

In [2]:
# 1  Импортируйте пакет numpy под именем np
import numpy as np

In [3]:
# 2  Создайте нулевой вектор размера 10
nul_v = np.zeros(10)
print(nul_v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# 3  Как узнать объем памяти любого массива
print(sys.getsizeof(nul_v))

184


In [7]:
# 4 Создайте вектор со значениями от 10 до 49
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# 5 Создайте обратный вектор из вектора в задании 4 (первый элемент становится последним)
v = np.arange(49, 9, -1)
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
# 6 Создайте матрицу 3x3 со значениями от 0 до 8
m = np.arange(0, 9).reshape(3, 3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
# 7 Найти индексы ненулевых элементов из [1,2,0,0,4,0]
a = np.array([1, 2, 0, 0, 4, 0])
print('\n', np.nonzero(a))


 (array([0, 1, 4]),)


In [14]:
# 8 Создайте массив 3x3x3 со случайными значениями
r = np.random.random((3, 3, 3)) * 100
print(r)

[[[94.82492094 97.78835033  8.10365637]
  [50.89618829 33.50718198 32.78546097]
  [40.49765574 48.69322655 54.23164328]]

 [[82.48512303 16.18038526 72.72575465]
  [73.415621   46.33386806 47.9567064 ]
  [10.7822918  50.904965   84.4184772 ]]

 [[85.20152116 45.29028903  3.86534903]
  [ 8.29047941 54.35489981 77.5511027 ]
  [69.06550155 94.30231986 20.45810258]]]


In [15]:
# 9 Создайте массив 10x10 со случайными значениями и найдите минимальное и
# максимальное значения
r = np.random.randint(1, 100, (10, 10))
print(r, '\n', 'max = ', r.max(), ', min = ', r.min())


[[28 60 57 38 49 75 12 64 63 78]
 [46 35 81 47 69 38 78 32 69 68]
 [22 54 17 21 97 61 52 71 50 12]
 [ 2 94 57 35 34 61 54 55 17 31]
 [98 70 61 11 16 39  9 26 85 72]
 [92 12  2 55 95 40 81 13 64 97]
 [ 9 93 55 89 95 77 20  2 27 59]
 [ 1 25 35 19 91  7 27 14  2 85]
 [68 95 33 60  6 13 35 23 85 11]
 [64 34 72 83 27 34 27 43 91 89]] 
 max =  98 , min =  1


In [18]:
# 10 Создайте случайный вектор размера 30 и найдите среднее значение
a = np.random.randint(1, 100, 30)
print(a, '\n', np.average(a))

[83 36 12 66 35 92 53 98 15 37 32 38 79 20 67 90 41 28 96 58 66  4 55  2
 64  1  4 98 10 35] 
 47.166666666666664


In [19]:
# 11 Создайте массив 2d 2x3 c 1 на границе и 0 внутри
# некорректное задание, сделаю 3х3
f = np.ones((3, 3))
f[1:-1, 1:-1] = 0
print(f)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [20]:
# 12 Каков результат следующего выражения?
print(0 * np.nan, np.nan == np.nan, np.inf > np.nan,
  np.nan - np.nan, np.nan in set([np.nan]), 0.3 == 3 * 0.1)


nan False False nan True False


In [21]:
# 13 Рассмотрим массив размера (6,7,8). Каков индекс (x,y,z) 100-го элемента?
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


In [22]:
# 14 Умножить матрицу 5x3 на матрицу 3x2
a = np.ones((5, 3))
b = np.ones((3, 2))
print(np.dot(a, b))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [24]:
# 15 Создайте одномерный массив со случайными значениями от 1 до 10,
# инвертируйте (поменяйте местами) все элементы, со значениями 3 и 8.
# странное задание, ну да ладно
a = np.random.randint(1, 11, 20)
print(a)
a[a == 3] = 12
a[a == 8] = 3
a[a == 12] = 8
print(a)

[ 8  6  3  1  3  6  7  9  6  1  5  9 10 10  7  5  4  6  4  2]
[ 3  6  8  1  8  6  7  9  6  1  5  9 10 10  7  5  4  6  4  2]


In [28]:
# 16 Каков результат следующих выражений?
print(np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float))

nan 0 [-9.22337204e+18]


<ipython-input-28-ec47f4d533a3>:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float))
<ipython-input-28-ec47f4d533a3>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float))


In [30]:
# 17 Как найти общие значения между двумя массивами?
a = np.random.randint(1, 11, 10)
b = np.random.randint(1, 11, 10)
print(f'Массив a:\n{a}\nМассив b:\n{b}\nОбщие значения: {np.intersect1d(a, b)}')

Массив a:
[10  3  1  5  2  6  9  3  8  9]
Массив b:
[ 5  6  3  1  9  3  1  7 10  6]
Общие значения: [ 1  3  5  6  9 10]


In [31]:
# 18 Как вычислить ((A+B)*(-A/2)) с заменой массива А (без копирования)?
a = np.ones(3)*1
b = np.ones(3)*2
c = np.ones(3)*3
np.add(a, b, out=b)
np.divide(a, 2, out=a)
np.negative(a, out=a)
np.multiply(a, b, out=a)
print(a)

[-1.5 -1.5 -1.5]


In [32]:
# 19 Создайте матрицу 5x5 со значениями строк от 0 до 4.
a = np.zeros((5, 5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [33]:
# 20 Создайте вектор размера 10 со значениями в диапазоне от 0 до 1, исключая 1 и 0
a = np.random.sample(10)
print(a)

[0.13077693 0.81091122 0.37830571 0.09035082 0.58881672 0.08488084
 0.51899323 0.83829893 0.34149971 0.40920539]


In [35]:
# 21 Создайте случайный вектор размера 10 и отсортируйте его
a = np.random.randint(1, 100, 10)
print(f'Исходный массив:\n{a}\nОтсортированный массив:\n{np.sort(a)}')

Исходный массив:
[ 1 96 26 50 97 39 24 82 49 25]
Отсортированный массив:
[ 1 24 25 26 39 49 50 82 96 97]


In [40]:
# 22 Можно ли суммировать небольшой массив быстрее, чем np.sum?
a = np.random.randint(1, 100, (500, 500))
start = time.time_ns()
np.sum(a)
finish = time.time_ns()
time1 = float(finish - start)
start = time.time_ns()
np.add.reduce(a)
finish = time.time_ns()
time2 = float(finish - start)
print(' Способ 1:', time1, '\n', 'Способ 2:', time2)

 Способ 1: 635321.0 
 Способ 2: 516238.0


In [37]:
# 23 Рассмотрим два случайных массива A и B, проверьте, равны ли они
a = np.random.randint(1, 11, 10)
b = np.random.randint(1, 11, 10)
print('Равны ли массивы?', np.allclose(a, b))

Равны ли массивы? False


In [43]:
# 24 Создайте случайный вектор размера 10 и замените максимальное значение на 0
a = np.random.randint(1, 11, 10)
print(f'Исходный массив:\n{a}')
a[a.argmax()] = 0
print(f'Итоговый массив:\n{a}')

Исходный массив:
[10  3  5  8  6 10  4 10  6  1]
Итоговый массив:
[ 0  3  5  8  6 10  4 10  6  1]


In [44]:
# 25 Распечатайте минимальное и максимальное представимое значение для каждого скалярного типа numpy
for dtype in [np.int8, np.int32, np.int64]:
   print(f'Тип: {dtype.__name__}, минимум: {np.iinfo(dtype).min}, максимум: {np.iinfo(dtype).max}')
for dtype in [np.float32, np.float64]:
   print(f'Тип: {dtype.__name__}, минимум: {np.finfo(dtype).min}, максимум: {np.finfo(dtype).max}, '
         f'и дельта: {np.finfo(dtype).eps}')

Тип: int8, минимум: -128, максимум: 127
Тип: int32, минимум: -2147483648, максимум: 2147483647
Тип: int64, минимум: -9223372036854775808, максимум: 9223372036854775807
Тип: float32, минимум: -3.4028234663852886e+38, максимум: 3.4028234663852886e+38, и дельта: 1.1920928955078125e-07
Тип: float64, минимум: -1.7976931348623157e+308, максимум: 1.7976931348623157e+308, и дельта: 2.220446049250313e-16


In [48]:
# 26 Как вывести все значения большого массива?
z = np.zeros((40, 40))
print('До:\n', z)
# np.set_printoptions(threshold=float('inf'))
print('После:\n', z)

До:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [53]:
# 27 Рассмотрим случайный вектор формы (100,2), представляющий координаты,
# найдите расстояния между точками
n = 100
c = np.zeros((100, 2), dtype='int32')
c[:, 0] = np.arange(n)
c[:, 1] = np.arange(n) * 5
print('Координаты точек: ', '\n', c)
t1 = int(input('Введите номер точки А: '))
t2 = int(input('Введите номер точки Б: '))
print('Расстояние от точки А до точки Б = ', math.sqrt(math.pow(abs(c[t1-1, 0] - c[t2-1, 0]), 2) +
      math.pow(abs(c[t1-1, 1] - c[t2-1, 1]), 2)))

Координаты точек:  
 [[  0   0]
 [  1   5]
 [  2  10]
 [  3  15]
 [  4  20]
 [  5  25]
 [  6  30]
 [  7  35]
 [  8  40]
 [  9  45]
 [ 10  50]
 [ 11  55]
 [ 12  60]
 [ 13  65]
 [ 14  70]
 [ 15  75]
 [ 16  80]
 [ 17  85]
 [ 18  90]
 [ 19  95]
 [ 20 100]
 [ 21 105]
 [ 22 110]
 [ 23 115]
 [ 24 120]
 [ 25 125]
 [ 26 130]
 [ 27 135]
 [ 28 140]
 [ 29 145]
 [ 30 150]
 [ 31 155]
 [ 32 160]
 [ 33 165]
 [ 34 170]
 [ 35 175]
 [ 36 180]
 [ 37 185]
 [ 38 190]
 [ 39 195]
 [ 40 200]
 [ 41 205]
 [ 42 210]
 [ 43 215]
 [ 44 220]
 [ 45 225]
 [ 46 230]
 [ 47 235]
 [ 48 240]
 [ 49 245]
 [ 50 250]
 [ 51 255]
 [ 52 260]
 [ 53 265]
 [ 54 270]
 [ 55 275]
 [ 56 280]
 [ 57 285]
 [ 58 290]
 [ 59 295]
 [ 60 300]
 [ 61 305]
 [ 62 310]
 [ 63 315]
 [ 64 320]
 [ 65 325]
 [ 66 330]
 [ 67 335]
 [ 68 340]
 [ 69 345]
 [ 70 350]
 [ 71 355]
 [ 72 360]
 [ 73 365]
 [ 74 370]
 [ 75 375]
 [ 76 380]
 [ 77 385]
 [ 78 390]
 [ 79 395]
 [ 80 400]
 [ 81 405]
 [ 82 410]
 [ 83 415]
 [ 84 420]
 [ 85 425]
 [ 86 430]
 [ 87 435]
 [ 88 440]


In [54]:
# 28 Как преобразовать массив с плавающей запятой (32 бита) в целое число (32 бита) с заменой?
Z = (np.random.rand(10)*100).astype(np.float32)
print('Исходный массив: \n', Z)
Y = Z.view(np.int32)
Y[:] = Z
print('Преобразованный массив: \n', Y)

Исходный массив: 
 [49.786057 92.8186   12.806065 86.07935  37.212692 96.91913  16.808224
 96.11649  11.980317 72.084236]
Преобразованный массив: 
 [49 92 12 86 37 96 16 96 11 72]


In [55]:
# 29 Создайте массив из следующего файла:
str1 = StringIO('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11''')
a = np.genfromtxt(str1, filling_values=0, delimiter=',', comments='#')
print(a)

[[ 1.  2.  3.  4.  5.]
 [ 6.  0.  0.  7.  8.]
 [ 0.  0.  9. 10. 11.]]


In [58]:
# 30 Вычтите среднее значение каждой строки случайной матрицы
x = 3
y = 3
a = np.random.sample((x, y)) * 100
print('Исходная матрица:\n',a)
for i in range(x):
    k = np.average(a[i])
    for j in range(y):
        a[i, j] = a[i, j] - k
print('Преобразованная матрица:\n', a)

Исходная матрица:
 [[26.26277958 67.15512075 95.41257794]
 [51.99155194 38.36867299  3.85078457]
 [85.6855005   2.49775222 50.69506481]]
Преобразованная матрица:
 [[-36.68071318   4.21162799  32.46908518]
 [ 20.5878821    6.96500316 -27.55288526]
 [ 39.39272799 -43.79502029   4.4022923 ]]


In [60]:
# 31 Рассмотрим случайный вектор, как добавить 1 к каждому элементу,
# индексированному вторым вектором (будьте осторожны с повторяющимися индексами)?
n = 20
a = np.zeros(n)
b = np.random.randint(1, n-1, n*2)
a += np.bincount(b, minlength=len(a))
print(f'Исходный вектор:\n{b}\nПреобразованный вектор:\n{a}')

Исходный вектор:
[18 15  4 11  7 15  3 10  6 15 11  6 15 15 12  4 17 18 15  6 12  5  8 12
  5 10  3  9 18 12  9 12  6  5  9  8  1 18 10  8]
Преобразованный вектор:
[0. 1. 0. 2. 2. 3. 4. 1. 3. 3. 3. 2. 5. 0. 0. 6. 0. 1. 4. 0.]


In [62]:
# 32 Как перенести элементы вектора (X) в массив (F) на основе списка индексов (I)?
n = 10
a = np.arange(n) * 2
b = np.zeros(n)
i = np.array([0, 5, 2, 6, 4])
b[i] = a[i]
print(f'Исходный вектор:\n{a}\nПреобразованный вектор:\n{b}')

Исходный вектор:
[ 0  2  4  6  8 10 12 14 16 18]
Преобразованный вектор:
[ 0.  0.  4.  0.  8. 10. 12.  0.  0.  0.]


In [64]:
# 33 Рассматривая четырехмерный массив, как получить сумму сразу (в одну операцию)
# по двум последним осям?
a = np.random.randint(1, 11, (3, 3, 3, 3))
sum2 = a.sum(axis=(-2, -1))
print(f'Вектор:\n{a}\nСумма:\n{sum2}')

Вектор:
[[[[ 2  2  2]
   [ 1  1  5]
   [ 9  6  1]]

  [[ 8  1  2]
   [ 6  8  8]
   [ 3  7  9]]

  [[ 4  4  6]
   [ 9  6  4]
   [ 9  1  1]]]


 [[[ 6 10 10]
   [ 9  9  6]
   [10  9  8]]

  [[ 2  4  9]
   [ 3  7  4]
   [ 3  6  7]]

  [[10  3  7]
   [ 3  7  6]
   [10  9  2]]]


 [[[ 1 10  2]
   [ 2  3  9]
   [ 6  4  4]]

  [[ 6 10  4]
   [ 6  3  5]
   [ 9 10  5]]

  [[ 8  6 10]
   [10  2  3]
   [ 6  7  4]]]]
Сумма:
[[29 52 44]
 [77 45 57]
 [41 58 56]]


In [65]:
# 34 Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор
# с 3 последовательными нулями, чередующимися между каждым значением?
a = np.arange(5) + 1
b = np.zeros(17)
b[4*a - 4] = a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [66]:
# 35 Рассмотрим массив размерности (5,5,3), как его умножить на массив размерностью (5,5)?
a = np.random.randint(1, 11, (5, 5, 3))
b = np.ones((5, 5))
print(a * b[:, :, None])

[[[ 1.  7.  2.]
  [ 9. 10.  6.]
  [10.  8.  5.]
  [ 8.  7.  7.]
  [ 5.  3.  8.]]

 [[ 2.  9.  3.]
  [ 3.  4.  4.]
  [ 8.  8.  8.]
  [ 5.  3.  9.]
  [ 2.  4.  6.]]

 [[ 2. 10.  4.]
  [ 9.  7.  3.]
  [10.  5.  9.]
  [ 6.  5.  7.]
  [10.  1.  3.]]

 [[ 5.  2.  5.]
  [ 3.  6.  1.]
  [ 1.  3.  6.]
  [ 2.  9. 10.]
  [ 8.  7.  5.]]

 [[ 1.  8.  1.]
  [ 2.  4.  7.]
  [ 1.  1.  8.]
  [ 5.  1.  8.]
  [ 7.  4.  3.]]]


In [69]:
# 36 Как вычислить средние значения, используя скользящее окно по массиву?
a = np.arange(20) + 1
ws = 6
cms_a = np.cumsum(a)
cms_a[ws:] = cms_a[ws:] - cms_a[:-ws]
cms_a = cms_a[ws - 1:] / ws
print(f'Исходный вектор:\n{a}\nРазмер окна:\n{ws}\nСредние по окну:\n{cms_a}')

Исходный вектор:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Размер окна:
6
Средние по окну:
[ 3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5 14.5 15.5 16.5
 17.5]


In [71]:
# 37 Рассмотрим одномерный массив Z, постройте из него двумерный массив,
# первая строка которого (Z[0],Z[1],Z[2]), а каждая последующая строка
# сдвинута на 1 (последняя строка должна быть (Z[ -3],Z[-2],Z[-1])
n = 3
a = np.random.randint(1, 11, 10)
sh = (a.size - n + 1, n)
st = (a.itemsize, a.itemsize)
b = np.lib.stride_tricks.as_strided(a, shape=sh, strides=st)
print(f'Исходный:\n{a}\nПреобразованный:\n{b}')

Исходный:
[ 4  8  1 10  2  4  4  7  3  2]
Преобразованный:
[[ 4  8  1]
 [ 8  1 10]
 [ 1 10  2]
 [10  2  4]
 [ 2  4  4]
 [ 4  4  7]
 [ 4  7  3]
 [ 7  3  2]]


In [74]:
# 38 Рассмотрим 2 набора точек P0,P1, описывающих линии (2d), и набор точек P.
# Как вычислить расстояние от каждой точки j (P[j]) до каждой линии i (P0[i],P1[i])?
n = int(input('Введите количество прямых: '))
m = int(input('Введите количество точек: '))
a = np.random.randint(0, 11, (n, 2))
b = np.random.randint(0, 11, (n, 2))
p = np.random.randint(0, 11, (m, 2))
print(f'Массив начальных точек прямых:\n{a}\nМассив конечных точек прямых:\n{b}\nМассив точек p:\n{p}')
for i in range(m):
    for j in range(n):
        w = np.cross((b[j]-a[j]), (p[i]-a[j]))
        s = np.linalg.norm(w)
        ab = np.linalg.norm(b[j]-a[j])
        d = s / ab
        print(f'Расстояние от точки {i+1} до прямой {j+1} = {d}')

Введите количество прямых: 2
Введите количество точек: 2
Массив начальных точек прямых:
[[ 6 10]
 [ 2  8]]
Массив конечных точек прямых:
[[8 0]
 [2 5]]
Массив точек p:
[[9 2]
 [2 1]]
Расстояние от точки 1 до прямой 1 = 1.3728129459672884
Расстояние от точки 1 до прямой 2 = 7.0
Расстояние от точки 2 до прямой 1 = 5.687367919007337
Расстояние от точки 2 до прямой 2 = 0.0


In [75]:
# 39 Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив
# R = [[1,2,3, 4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
n = 4
a = np.arange(14) + 1
sh = (a.size - n + 1, n)
st = (a.itemsize, a.itemsize)
b = np.lib.stride_tricks.as_strided(a, shape=sh, strides=st)
print(f'Исходный массив:\n{a}\nПреобразованный массив:\n{b}')

Исходный массив:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Преобразованный массив:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [79]:
# 40 Найдите ранг случайной матрицы
A = np.random.randint(1, 3, (3, 3))
print(f"Матрица А:\n{A}\nРанг матрицы A:\n{np.linalg.matrix_rank(A, tol=None)}")

Матрица А:
[[1 2 2]
 [1 2 2]
 [2 1 1]]
Ранг матрицы A:
2


In [80]:
# 42 Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A,
# содержащие элементы каждой строки B, независимо от порядка элементов в B?
a = np.random.randint(1, 7, (8, 3))
b = np.random.randint(1, 7, (2, 2))
print(f'Массив а:\n{a}\nМассив b:\n{b}')
c = (a[..., np.newaxis, np.newaxis] == b)
i = np.where(c.any((3, 1)).all(1))[0]
print(f'Индексы искомых строк:\n{i}')

Массив а:
[[4 2 3]
 [2 1 6]
 [3 6 6]
 [5 4 6]
 [1 2 1]
 [6 4 4]
 [5 1 3]
 [5 6 5]]
Массив b:
[[5 1]
 [6 5]]
Индексы искомых строк:
[1 3 6 7]


In [81]:
# 43 Как извлечь уникальные значения из 2-х двумерных массивов?
a = np.random.randint(1, 10, (4, 2))
print(f'Массив:\n{a}\nУникальные значения:\n{np.unique(a)}')
# Уникальные строки?
b = np.random.randint(0, 2, (5, 2))
print(f'Массив:\n{b}\nУникальные строки:\n{np.unique(b, axis=0)}')

Массив:
[[6 7]
 [5 5]
 [8 7]
 [2 8]]
Уникальные значения:
[2 5 6 7 8]
Массив:
[[1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]]
Уникальные строки:
[[0 1]
 [1 0]
 [1 1]]
